language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true docker-react npm run test -- --coverage
deploy:
    - provider: heroku
        api_key: $HEROKU_API_KEY
            # secure: Zto6H/GvwOD6mx4UhSOdJ1JWUP3Piy3D0GEGvCA49+JvwPGxJKiRgCUz/zinttel7OUYhjclLldkYhefQ3J8hbajMSpvgZeLhwVMseocnzaLB83JJc5hWpFC9eYHgGwCPnFDJFrBf4XpWWyqkcoB2l+B/+lRnz2PzekfDZ7b93s+yTxzQRuFTjL/UN4KZR4mrbOwuFBTrhJfipZpsJW22FCqNkToOkzcLR9ZVe0+c+i4QHqrRGiB1EYkA8NWfjLcpCG/cFJ99C0ZLsDKHnSRhRhme5NOjwe2pV1UVE/Oj3vf5Uqg8VwoDZJO8dWp83wS6WS4Lcm3fb1OGzu0IwfNPQs1dWWkDCj1KmcOrbhdNjaTkX0+4WZw+EfffbBICNrrtOBzluqSqXqZtLbv6zkH4n7q7XzsRDa/adGfg4e2CQsgZt/xpHfE6xb7tERP0p0BpRnQNgSErLiNFPk0hSCUKBPhDEHz7qdVbd5Q7it8xVPRxB/FLtDzvjrk7/oe+NacTEmu8RFhy6aLz8DE9nh65+k4mg2pQ6abgYk23ZaWYOOc/fjbLxoL7TfRGab77Ul7+P2ucXGpwxioN3Fu7WIVQATizgjHpfU13A2AffULEnSfbDgTt2isnJLbIhFBXs04kgPW38j2iiOIXseb9rvV2QROCqsSQCs/ASgkx94Zk00=
        app: my-react-docker
        on:
            branch: master

# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "docker-react"
#     env: "DockerReact-env"
#     bucket_name: "elasticbeanstalk-us-east-2-160071257600"
#     bucket_path: "docker-react"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY